import { z } from 'zod';

export const ErrorCodeSchema = z.enum([
  'INVALID_REQUEST', 'INVALID_RESPONSE', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND',
  'PROJECT_REQUIRED', 'PROJECT_TICKET_INVALID', 'PROJECT_VOLUME_UNSUPPORTED', 'PROJECT_UNTRUSTED', 'PROJECT_NOT_FOUND', 'PROJECT_MISSING',
  'SESSION_NOT_FOUND', 'PROFILE_NOT_FOUND', 'INVALID_ENDPOINT', 'CLOUD_NOT_ALLOWED', 'RESEARCH_NOT_ALLOWED',
  'REVIEW_NOT_AVAILABLE', 'REVIEW_NOT_READY', 'REVIEW_WORKSPACE_TOO_LARGE', 'STALE_VERIFICATION', 'RESEARCH_KIT_UNAVAILABLE',
  'DOCUMENT_NOT_AVAILABLE', 'DOCUMENT_UNVERIFIED', 'DOCUMENT_UNSAFE', 'DOCUMENT_REDACTION_UNAVAILABLE', 'DOCUMENT_TOO_LARGE', 'PURGE_NOT_ALLOWED', 'PURGE_INCOMPLETE',
  'RUN_CANCELLED', 'RUN_ACTIVE', 'RUN_NOT_FOUND', 'REQUEST_CONFLICT', 'STALE_REVISION',
  'ENGINE_UNAVAILABLE', 'ENGINE_EPOCH_STALE', 'NOT_IMPLEMENTED', 'ENCRYPTION_UNAVAILABLE',
  'CREDENTIAL_UNAVAILABLE', 'CREDENTIAL_REVOKED', 'COLLECTOR_TOKEN_REQUIRED', 'PROVIDER_ERROR', 'PROVIDER_UNAVAILABLE', 'PROVIDER_PROTOCOL_ERROR',
  'CONTEXT_LIMIT', 'BUDGET_EXCEEDED', 'APPROVAL_REQUIRED', 'APPROVAL_STALE', 'APPROVAL_DENIED',
  'PATH_OUTSIDE_PROJECT', 'HARDLINK_REVIEW_REQUIRED', 'FILE_CONFLICT', 'FILE_TOO_LARGE', 'UNSUPPORTED_ENCODING', 'UNDO_UNAVAILABLE',
  'GIT_UNAVAILABLE', 'COMMAND_FAILED', 'COMMAND_TIMEOUT', 'COMMAND_UNKNOWN', 'COMMAND_UNAVAILABLE', 'COMMAND_CHANGED', 'CANCEL_PENDING', 'REMOTE_STATE_UNKNOWN',
  'MODEL_UNAVAILABLE', 'MODEL_UNQUALIFIED', 'STORAGE_FULL', 'UPDATE_NOT_QUIESCENT', 'NETWORK_ERROR', 'TIMEOUT',
  'INTERNAL_ERROR', 'RECOVERY_REQUIRED', 'SNAPSHOT_QUOTA', 'SNAPSHOT_CORRUPT',
]);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;
export const RetryPolicySchema = z.enum(['never', 'same-request', 'after-reconcile']);
export type RetryPolicy = z.infer<typeof RetryPolicySchema>;
export const PublicErrorSchema = z.object({ code: ErrorCodeSchema, message: z.string().min(1).max(2048), retry: RetryPolicySchema }).strict();
export type PublicError = z.infer<typeof PublicErrorSchema>;
